# Generated by Django 5.0.1 on 2024-01-25 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stocks",
            fields=[
                ("code", models.CharField(max_length=10)),
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("val_open", models.TextField(null=True)),
                ("val_close", models.TextField(null=True)),
                ("val_high", models.TextField(null=True)),
                ("val_low", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FavStocks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference",
                        to="bsestox.stocks",
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StocksCurrVal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("val_curr", models.FloatField()),
                ("date", models.DateField()),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_stock",
                        to="bsestox.stocks",
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
