# Generated by Django 5.0.1 on 2024-01-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsestox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='val_curr',
            new_name='val_high',
        ),
        migrations.AddField(
            model_name='stocks',
            name='val_low',
            field=models.TextField(null=True),
        ),
    ]
