# Generated by Django 5.0.1 on 2024-01-25 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bsestox", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockscurrval",
            name="name",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="bsestox.stocks"
            ),
        ),
    ]
